//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garcon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public Merchant()
        {
            this.Tables = new HashSet<Table>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public string contactPhone { get; set; }
        public string contactName { get; set; }
    
        public virtual ICollection<Table> Tables { get; set; }
    }
}
