//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garcon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int id { get; set; }
        public int tableId { get; set; }
        public System.DateTime openDateTime { get; set; }
        public Nullable<System.DateTime> closeDateTime { get; set; }
        public decimal taxAmount { get; set; }
        public decimal totalAmount { get; set; }
        public decimal amount { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Table Table { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
