//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garcon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string beaconId { get; set; }
        public string description { get; set; }
        public bool available { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
