//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garcon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCard
    {
        public UserCard()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public string cardType { get; set; }
        public string description { get; set; }
        public string fakeDigits { get; set; }
        public string fakeCVV2 { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual User User { get; set; }
    }
}
